language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: false
      osx_image: xcode7.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - qt5-default
      - libqt5opengl5-dev
      - xorg-dev
      - lib32stdc++6 # For CMake

cache:
  directories:
    - "$HOME/.local"

install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"

deploy:
  provider: bintray
  file: "${HOME}/build/${TRAVIS_REPO_SLUG}/.travis.descriptor.json"
  user: citra-emu
  key:
    secure: "MADIMRKlcr+O2iCmavkbIvUWexopOhnzXuDHKXfGyGY93Im8NCTrbb3tDoLH+bRYQrjNCeaV36ffhpDULU+eH11L4yF5/KY4modEKW4sq3cnAJkm5DUOc/sujlRCwzfjg6NFZGhjxfSlt0ltKRdCKEB/j1vR2GD7d/eQ4diJukQ="