language: cpp
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
    - os: osx
      sudo: false
      osx_image: xcode7.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - qt5-default
      - libqt5opengl5-dev
      - xorg-dev
      - lib32stdc++6 # For CMake

cache:
  directories:
    - "$HOME/.local"

install: "./.travis-deps.sh"
script: "./.travis-build.sh"
after_success: "./.travis-upload.sh"

deploy:
  provider: bintray
  file: "${HOME}/build/${TRAVIS_REPO_SLUG}/.travis.descriptor.json"
  user: citra-emu
  key:
    secure: "gLwHYfbTNILaI89sB9nnM+XpDGV4oadWUJvuPuMzKWpkYdiGW1HXptLlSWmQOkfAI5v25q0JcTbFq4Afxk7C4AHp+wxgISsbFcwoUUe00r0MJWKJwiJmZTbgeeyk8abr1t14h1g2rOcwVPqwdjHXZu84X3fhnukL0KzgfDym4S8="